# Generated by Django 5.1.1 on 2024-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expensiveapp', '0002_users_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_register',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
