[tool.pyright]
include = ["Expensive_tracker", "Expensiveapp"]
exclude = ["**/node_modules", "**/__pycache__", "**/.git", "myvenv"]
pythonVersion = "3.13"
pythonPlatform = "Windows"
venvPath = "."
venv = "myvenv"
reportMissingImports = "none"
reportMissingTypeStubs = "none"
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
reportAttributeAccessIssue = "none"
reportArgumentType = "none"
reportRedeclaration = "warning"
extraPaths = ["./myvenv/Lib/site-packages", "."]

[tool.basedpyright]
include = ["Expensive_tracker", "Expensiveapp"]
exclude = ["**/node_modules", "**/__pycache__", "**/.git", "myvenv"]
pythonVersion = "3.13"
pythonPlatform = "Windows"
venvPath = "."
venv = "myvenv"
reportMissingImports = "none"
reportMissingTypeStubs = "none"
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
reportAttributeAccessIssue = "none"
reportArgumentType = "none"
reportRedeclaration = "warning"
extraPaths = ["./myvenv/Lib/site-packages", "."]
